###
GET http://localhost:3000/tasks?page=1&limit=5
    

###
GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks/3


###
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImVtYWlsIjoidGVzdDVAbWFpbC5ydSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzc0MTA0MTY3LCJleHAiOjE3NzQ3MDg5Njd9.iGGrAO3b7WXxsNONepqH9T1p3zKWFGpgPIG9_chbnBg

{
    "title": ""
}

###
PATCH http://localhost:3000/tasks/3
Content-Type: application/json

{
    "title": "Обновленная задача"
}

###
DELETE http://localhost:3000/tasks/3
Content-Type: application/json

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Тест5",
    "email": "test5@mail.ru"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test5@mail.ru",
    "password": "qwerty123"
}


